name: run shell commands

on:
  push:
    branches: [master]

jobs:
  shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo string
        run: echo "Hello this first github action workflow"
